baseurl = "https://rprofile.net/"
title = "Rprofile"
author = "Georgios Karamanis"
canonifyurls = true
languagecode = "en"
paginate = 3
theme = "renga"

enableEmoji = true
hasCJKLanguage = true

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
pagetitle = "Rprofile"
# copyright = "© 2020 Georgios Karamanis"
# copyrightUrl = "https://nanx.me/hugo-renga/"
faviconfile = "images/favicon.png"
logofile = "images/logo.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "gkaramanis/Rprofile_net"
twitter = "rprofile_net"
# linkedin = "nanxstats"
email = "rprofile@karaman.is"

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Interviews"
url = "/blog/"
weight = 2
