baseurl = "https://rprofile.net/"
title = "Rprofile"
author = "Georgios Karamanis"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = "UA-727326-26"
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Rprofile"

[[menu.main]]
    name = "Home"
    url = "https://rprofile.net"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/gkaramanis/Rprofile_net"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Rprofile_net"
    weight = 3
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
